// Code generated by "stringer -type=TallyStatus"; DO NOT EDIT.

package vmixtcp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[Program-1]
	_ = x[Preview-2]
}

const _TallyStatus_name = "OffProgramPreview"

var _TallyStatus_index = [...]uint8{0, 3, 10, 17}

func (i TallyStatus) String() string {
	if i >= TallyStatus(len(_TallyStatus_index)-1) {
		return "TallyStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TallyStatus_name[_TallyStatus_index[i]:_TallyStatus_index[i+1]]
}
